server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  datasource:
    url: jdbc:mysql://localhost:3306/ms-content?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
keycloak:
  enabled: false
logging:
  level:
    root: info
    com.itmuch: debug