server:
  port: 9488
spring:
  application:
    name: zipkin-server
management:
  security:
    enabled: false

zipkin:
  collector:
    kafka:
      # ZooKeeper host string, comma-separated host:port value.
      bootstrap-servers: localhost:9092
      # Name of topic to poll for spans
      topic: zipkin-topic
      # Consumer group this process is consuming on behalf of.
      group-id: zipkin-group
      # Count of consumer threads consuming the topic
      streams: 1
      # Maximum size of a message containing spans in bytes
      max-message-size: 1048576
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1
      date-separator: '-'